package constant

// indonesianAirports is a map of Indonesian airport codes to their names for medium and large airports
var indonesianAirports = map[string]string{
	"DPS": "Denpasar",
	"CGK": "Jakarta",
	"SUB": "Surabaya",
	"JOG": "Yogyakarta",
	"LOP": "Mataram (Pujut, Lombok Tengah)",
	"HLP": "Jakarta",
	"UPG": "Makassar",
	"KNO": "Beringin",
	"MES": "Medan",
	"MDC": "Manado",
	"BDO": "Bandung",
	"DJJ": "Sentani",
	"SOC": "Surakarta",
	"SRG": "Semarang",
	"PLM": "Palembang",
	"BPN": "Balikpapan",
	"BTJ": "Banda Aceh",
	"BTH": "Batam",
	"PDG": "Padang (Katapiang)",
	"WMX": "Wamena",
	"PKU": "Pekanbaru",
	"KOE": "Kupang",
	"AMQ": "Ambon",
	"BIK": "Biak",
	"PNK": "Pontianak",
	"BDJ": "Banjarbaru",
	"SOQ": "Sorong",
	"TIM": "Timika",
	"MLG": "Malang",
	"MKW": "Manokwari",
	"TTE": "Ternate",
	"CXP": "Cilacap",
	"TKG": "Bandar Lampung",
	"MKQ": "Merauke",
	"GNS": "Gunungsitoli",
	"PKY": "Palangkaraya",
	"KTG": "Ketapang",
	"PLW": "Palu",
	"OKL": "Oksibil",
	"PGK": "Pangkal Pinang",
	"TRK": "Tarakan",
	"YIA": "Yogyakarta",
	"BKS": "Bengkulu",
	"NAH": "Tabukan Utara, Sangihe Islands",
	"AAP": "Samarinda",
	"TNJ": "Tanjung Pinang-Bintan Island",
	"LUW": "Luwok",
	"DHX": "Kediri",
	"FKQ": "Fakfak",
	"KNG": "Kaimana",
	"DUM": "Dumai",
	"KJT": "Kertajati",
	"MEQ": "Kuala Pesisir",
	"AEG": "Padang Sidempuan",
	"BEJ": "Tanjung Redeb - Borneo Island",
	"RGT": "Rengat-Sumatra Island",
	"PSU": "Putussibau-Borneo Island",
	"PDO": "Talang Gudang-Sumatra Island",
	"BMU": "Bima",
	"KXB": "Kolaka",
	"LUV": "Langgur",
	"NAM": "Namniwel",
	"NPO": "Nanga Pinoh-Borneo Island",
	"FLZ": "Sibolga (Pinangsori)",
	"SQG": "Sintang",
	"TXE": "Takengon",
	"TMH": "Tanah Merah",
	"TJG": "Tanta-Tabalong",
	"WNI": "Wangi-wangi Island",
	"BXB": "Babo",
	"PSJ": "Poso-Celebes Island",
	"NTX": "Ranai-Natuna Besar Island",
	"UGU": "Bilogai",
	"LSR": "Kutacane",
	"TRT": "Toraja",
	"OTI": "Gotalalamo-Morotai Island",
	"LSX": "Lhok Sukon-Sumatra Island",
	"NBX": "Nabire",
	"ZRI": "Serui",
}

// GetAirportCity returns the city name for an Indonesian airport code.
func GetAirportCity(code string) (string, bool) {
	city, ok := indonesianAirports[code]
	return city, ok
}
